[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.5.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
paste = "1.0.11"
bitflags = "1.3.2"
buddy_system_allocator = "0.9.0"
linked_list_allocator = "0.10.4"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"