[build]
# target = "config/os-target.json"
target = "x86_64-unknown-none"
rustflags = [
  "-Cforce-unwind-tables",
  "-Clink-arg=-Wl,eh_frame.ld",
]


[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]